import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const read = (path: string) => readFileSync(join(process.cwd(), path), 'utf8');

test('root layout exposes the Bing Webmaster verification tag through metadata', () => {
  const rootLayout = read('src/app/layout.tsx');

  assert.match(
    rootLayout,
    /other:\s*\{[\s\S]*'msvalidate\.01':\s*'0D6AAD46F945AF92BE8D6CBF6D477A8C'[\s\S]*\}/
  );
  assert.doesNotMatch(
    rootLayout,
    /<meta\s+name="msvalidate\.01"/,
    'Bing verification should be generated by Next metadata instead of the manual head'
  );
});
