import Link from 'next/link';
import VogueLegalPage from '@/components/legal/VogueLegalPage';
import { getLanguageAlternates, getUrlWithLocale } from '@/lib/urls/urls';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import messages from '../../../messages/en.json';

const PAGE_PATH = '/terms-of-service';
const title = 'Terms of Service - Vogue AI';
const description =
  'Read the Vogue AI terms for prompt gallery browsing, AI image generation, credits, payments, refunds, and content safety rules.';

export async function generateTermsOfServiceMetadata(
  locale: string
): Promise<Metadata> {
  const localizedPath = getUrlWithLocale(PAGE_PATH, locale);

  return {
    title,
    description,
    alternates: {
      canonical: localizedPath,
      languages: getLanguageAlternates(PAGE_PATH),
    },
    openGraph: {
      title,
      description,
      url: localizedPath,
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
    },
  };
}

export function generateMetadata(): Promise<Metadata> {
  return generateTermsOfServiceMetadata('en');
}

const sections = [
  {
    title: '1. Service scope',
    body: [
      'Vogue AI provides an AI prompt gallery, an image generation workspace, reference-image upload tools, generated asset history, and account-based credits for creative workflows.',
      'The Service includes AI image prompts, reference images, generated outputs, prompt metadata, model parameters, account features, credits, subscriptions, and one-time credit packs.',
      'AI outputs are generated by third-party model providers and may vary even when the same prompt or reference is used. We do not guarantee that any generated output will meet a specific artistic, commercial, legal, or technical result.',
    ],
  },
  {
    title: '2. Accounts and access',
    body: [
      'You are responsible for keeping your account, email login, Google OAuth login, password reset links, and session access secure.',
      'You must provide accurate account information and may not create accounts for abusive automation, payment fraud, policy evasion, scraping, or resale of access.',
      'We may suspend, limit, or terminate accounts that create operational risk, violate these Terms, misuse payment systems, or attempt to bypass model-provider or platform safety rules.',
    ],
  },
  {
    title: '3. Prompt gallery and indexed content',
    body: [
      'The gallery may include curated prompt examples, public reference images, model labels, source links, and metadata used to help users discover creative workflows.',
      'Some gallery items may be based on public creative material or community-shared examples. Creators or rights holders can request correction or removal by contacting support@vogueai.net with the relevant URL, ownership details, and requested action.',
      'You may use gallery prompts as creative inspiration, but you are responsible for checking whether a prompt, image, brand, character, likeness, or generated output is appropriate for your intended use.',
    ],
  },
  {
    title: '4. Prompt and output safety rules',
    body: [
      'You may not use Vogue AI to create, upload, request, or distribute illegal content, child sexual content, non-consensual intimate imagery, sexual services, graphic violence, self-harm instructions, terrorism, violent extremism, hate, harassment, or targeted abuse.',
      'You may not use the Service for weapon construction, drug manufacturing, fraud, impersonation, deepfakes that mislead viewers, privacy violations, doxxing, political deception, or any activity that violates applicable law.',
      'You may not generate or distribute content that infringes copyright, trademark, publicity rights, privacy rights, or other third-party rights, including unauthorized brand impersonation, counterfeit product imagery, or misleading celebrity or real-person endorsements.',
      'Model providers may apply stricter safety policies than Vogue AI. A prompt may be blocked, altered, refused, delayed, or reviewed when it conflicts with platform, provider, legal, payment, or community-safety requirements.',
    ],
  },
  {
    title: '5. User content and generated outputs',
    body: [
      'You retain the rights you already have in prompts, uploads, and generated outputs, subject to these Terms, provider restrictions, and applicable law.',
      'For compliant generated outputs, Vogue AI does not claim ownership over your generated images. You are responsible for confirming that your use, publication, resale, advertising, or commercial deployment of any output is lawful and does not infringe third-party rights.',
      'AI-generated content may contain mistakes, artifacts, biased elements, recognizable styles, inaccurate text, or unintended similarities. You should review outputs before publication or commercial use.',
    ],
  },
  {
    title: '6. Payments, credits, and refunds',
    body: [
      'Vogue AI may sell credits, subscriptions, and one-time credit packs. Payments may be processed through Stripe, ZPAY, Alipay, and WeChat Pay depending on your selected checkout method and region.',
      'Credits are virtual goods used to access generation services. Purchased credits are delivered to your account after successful payment, are not cash equivalents, are non-transferable, and cannot be exchanged for cash.',
      'Because generation results involve inherent model randomness, dissatisfaction with an output, low usage after purchase, device issues, network issues, or a policy refusal caused by your prompt normally does not qualify for a refund.',
      'Refunds may be considered for duplicate charges caused by payment-system error, extended platform outages that make core AI generation unavailable for more than 72 continuous hours, mistaken platform-side account restrictions, or other situations required by law.',
      'Refund requests must be sent to support@vogueai.net with order information, payment amount, transaction ID if available, and a clear description of the issue. Approved refunds are returned through the original payment method when technically possible.',
    ],
  },
  {
    title: '7. Availability and changes',
    body: [
      'We may change models, credit prices, plan limits, free-credit rules, prompt-gallery availability, upload limits, provider routing, or generation parameters as the Service evolves.',
      'Some features may depend on third-party providers, payment processors, cloud storage, or network availability. Temporary outages, provider rate limits, and model changes may affect generation speed or quality.',
      'We may update these Terms by posting a revised version on this page. Continued use of the Service after the effective date means you accept the updated Terms.',
    ],
  },
  {
    title: '8. Disclaimers and limitation of liability',
    body: [
      'The Service is provided on an as-is and as-available basis. To the fullest extent permitted by law, Vogue AI disclaims warranties of merchantability, fitness for a particular purpose, non-infringement, uninterrupted operation, and error-free outputs.',
      'To the fullest extent permitted by law, Vogue AI is not liable for indirect, incidental, special, consequential, punitive, lost-profit, lost-data, business interruption, reputational, or third-party claim damages arising from use of the Service.',
      'Nothing in these Terms limits liability that cannot be limited under applicable law.',
    ],
  },
];

export function TermsOfServicePageContent({ locale }: { locale: string }) {
  return (
    <VogueLegalPage
      title="Terms of Service"
      effectiveDate="May 21, 2026"
      intro={
        <>
          By accessing or using Vogue AI, you agree to these Terms, our{' '}
          <Link
            href={getUrlWithLocale('/privacy-policy', locale)}
            className="font-semibold text-slate-950 underline-offset-4 hover:underline"
          >
            Privacy Policy
          </Link>
          , and any checkout, provider, or feature-specific rules shown in the product.
        </>
      }
      sections={sections}
      contactTitle="9. Contact"
      contactBody={
        <p>
          Questions, refund requests, rights requests, or content removal
          requests should be sent to{' '}
          <a
            href="mailto:support@vogueai.net"
            className="font-semibold text-slate-950 underline-offset-4 hover:underline"
          >
            support@vogueai.net
          </a>
          .
        </p>
      }
    />
  );
}

export default function TermsOfServiceFallbackPage() {
  return (
    <NextIntlClientProvider locale="en" messages={messages}>
      <TermsOfServicePageContent locale="en" />
    </NextIntlClientProvider>
  );
}
