'use client';

export default function HailuoFAQ() {
  const faqs = [
    {
      question: 'What is Hailuo AI?',
      answer: 'Hailuo AI is an advanced AI-powered video generation platform that allows users to create short-form videos using simple text prompts. Hailuo AI technology is designed for quick and easy video creation, with applications ranging from artistic projects to educational content.',
    },
    {
      question: 'How does Hailuo AI text-to-video feature work?',
      answer: 'Hailuo AI uses advanced artificial intelligence to convert your text prompts into videos. You simply enter a detailed description, and the Hailuo AI system generates a video based on that description. The Hailuo AI platform uses state-of-the-art machine learning technologies for high-quality output.',
    },
    {
      question: 'Do I need to create an account to use Hailuo AI?',
      answer: 'No, registration is not required to use Hailuo AI. You can generate videos directly from the platform without signing up, making it incredibly accessible for all users.',
    },
    {
      question: 'What type of videos can I create with Hailuo AI?',
      answer: 'Hailuo AI is ideal for creating short videos for artistic, educational, and creative purposes. It\'s perfect for rapid prototyping and generating unique visuals for personal or professional use, including character animations, landscapes, and creative scenes.',
    },
    {
      question: 'How long does it take to generate a video with Hailuo AI?',
      answer: 'Video generation typically takes a few minutes depending on the complexity of the prompt and system demand. Most users can expect to wait up to 7 minutes for video generation, though our platform optimizes for faster processing.',
    },
    {
      question: 'What file formats are available for downloaded videos?',
      answer: 'Once your video is generated, you can download it in standard video format, typically MP4, which is compatible with most devices and platforms.',
    },
    {
      question: 'Can I use the videos generated by Hailuo AI for commercial purposes?',
      answer: 'At present, Hailuo AI is mainly intended for personal, educational, and artistic use. For commercial use, you may need to check specific terms and conditions or contact support for guidance.',
    },
    {
      question: 'Does Hailuo AI support languages other than English?',
      answer: 'Yes, Hailuo AI supports multiple languages. In fact, it is recommended to use prompts in Chinese for more accurate results as the platform is optimized for that language, though English prompts work well too.',
    },
    {
      question: 'Is Hailuo AI available globally?',
      answer: 'Yes, Hailuo AI is accessible to users worldwide. However, some regions may experience limited access or slower processing times due to server demand.',
    },
    {
      question: 'What kind of technology powers Hailuo AI?',
      answer: 'Hailuo AI uses state-of-the-art artificial intelligence and machine learning technologies to convert text into high-quality short videos. The platform is constantly being improved to enhance video output quality and efficiency.',
    },
  ];

  return (
    <section id="faq" className="py-20 bg-gradient-to-b from-gray-800 to-gray-900">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Frequently Asked Questions</h2>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Everything you need to know about Hailuo AI access on VogueAI.
          </p>
        </div>

        <div className="max-w-4xl mx-auto">
          <div className="space-y-6">
            {faqs.map((faq, index) => (
              <details
                key={index}
                className="group bg-gray-800 border border-gray-700 rounded-2xl overflow-hidden hover:bg-gray-750 hover:border-gray-600 transition-all duration-300"
              >
                <summary className="flex items-center justify-between p-6 cursor-pointer list-none hover:bg-gray-700 transition-colors">
                  <h3 className="text-lg font-semibold text-white pr-4">
                    {faq.question}
                  </h3>
                  <div className="flex-shrink-0 w-8 h-8 bg-gradient-to-r from-green-500 to-blue-500 rounded-full flex items-center justify-center">
                    <svg
                      className="w-4 h-4 text-white transform group-open:rotate-45 transition-transform duration-200"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                    </svg>
                  </div>
                </summary>
                <div className="px-6 pb-6 border-t border-gray-700">
                  <p className="text-gray-300 leading-relaxed pt-4">
                    {faq.answer}
                  </p>
                </div>
              </details>
            ))}
          </div>
        </div>

        <div className="mt-16 text-center">
          <p className="text-gray-300 mb-4">Ready to start creating professional videos with Hailuo AI technology? Experience the power of Hailuo AI video generation today!</p>
          <a
            href="#dashboard"
            className="inline-flex items-center text-green-400 hover:text-green-300 font-medium transition-colors duration-200"
          >
            Start generating videos now
            <svg className="ml-1 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
            </svg>
          </a>
        </div>
      </div>
    </section>
  );
}
